name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0
      - name: Set up JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: zulu
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Lint
        run: ./gradlew lintKotlin --stacktrace

  api_check:
    name: API check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3.1.0
      - name: Set up JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: zulu
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: API check
        run: ./gradlew apiCheck --stacktrace

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: set up JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: zulu
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :bindable:build --stacktrace
      - name: Unit tests
        run: ./gradlew :bindable:test --stacktrace
